fixing an environmnet issue in pipeline

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -1,13 +1,16 @@
 name: EKS Infrastructure Pipeline
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
-    branches: [ "main", "dev", "feature/infra-creation" ]
+    branches:
+      - main
+      - dev
+      - feature/infra-creation
+
   pull_request:
-    branches: [ "main", "dev"]
-    
+    branches:
+      - main
+      - dev
 
 permissions:
   id-token: write
@@ -19,6 +22,7 @@ env:
   TF_INPUT: false
 
 jobs:
+
   set-environment:
     runs-on: ubuntu-latest
 
@@ -28,6 +32,7 @@ jobs:
     steps:
       - name: Set environment
         id: set_env
+        shell: bash
         run: |
           echo "STARTED: Setting environment based on branch..."
 
@@ -38,7 +43,9 @@ jobs:
             BRANCH="${GITHUB_REF#refs/heads/}"
           fi
 
-          # Map branch directly to environment
+          echo "Detected branch: $BRANCH"
+
+          # Map branch to environment
           if [[ "$BRANCH" == "main" ]]; then
             echo "Branch '$BRANCH' detected -> setting environment to prod"
             ENV="prod"
@@ -46,20 +53,38 @@ jobs:
           elif [[ "$BRANCH" == "dev" ]]; then
             echo "Branch '$BRANCH' detected -> setting environment to dev"
             ENV="dev"
+
+          elif [[ "$BRANCH" == "feature/infra-creation" ]]; then
+            echo "Branch '$BRANCH' detected -> setting environment to dev"
+            ENV="dev"
+
+          else
+            echo "ERROR: Unsupported branch '$BRANCH'"
+            exit 1
           fi
 
-          echo "Branch": $BRANCH
+          echo "Branch: $BRANCH"
+          echo "Environment: $ENV"
+
+          # Set job output
           echo "env_name=$ENV" >> "$GITHUB_OUTPUT"
+
+          # Verify output
+          echo "GitHub output:"
+          cat "$GITHUB_OUTPUT"
+
 
   Terraform:
     name: Terraform checks
     runs-on: ubuntu-latest
+
     needs: set-environment
 
     environment:
       name: ${{ needs.set-environment.outputs.env_name }}
 
     steps:
+
       - name: Checkout repository
         uses: actions/checkout@v5
 
@@ -71,7 +96,7 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v6
         with:
           role-to-assume: arn:aws:iam::515020253576:role/GitHubActions-Terraform
-          aws-region: us-east-1
+          aws-region: ${{ env.AWS_REGION }}
           audience: sts.amazonaws.com
 
       - name: Verify AWS identity
